### ISSUE TITLE
HCI socket ERROR

### ISSUE THREAD

**Issue by MinnCho** [petzval/btferret#1]
Hi,

I'm currently doing a project on BLE mesh networks, and your interface seems perfect for this.
However I keep getting the following errors:

Initialising...
Bluez down failed
Bind failed
HCI socket ERROR - no Bluetooth?

What would the problem be and how can I fix it?

**Comment by petzval** [comment]
Yes, this should have been in the documentation - btferret must be run with root privileges from root or via sudo as follows:

sudo ./btferret

**Comment by petzval** [comment]
btferret must be run with root privileges from root, or via sudo as follows:

sudo ./btferret

Thanks for flagging up this issue, the documentation will be updated.
