### ISSUE TITLE
Gatt server uuid configuration?

### ISSUE THREAD

**Issue by gregoiregentil** [petzval/btferret#19]
A very important configuration is the Gatt server uuid. It's important because if you use the web bluetooth api, you can filter by service uuid.

Right now, the value is hard-coded in line https://github.com/petzval/btferret/blob/main/btlib.c#L669 and also line https://github.com/petzval/btferret/blob/main/btlib.c#L6592.

I think that it would make sense to add one line in devices.txt, something like: gatt uuid=....

**Comment by petzval** [comment]
Another sensible suggestion. I should be able to add this in the next release.

**Comment by gregoiregentil** [comment]
Thank you. Great work!
