### ISSUE TITLE
Function declaration doesn't match implementation. Causes compile to fail

### ISSUE THREAD

**Issue by fabianmejia** [petzval/btferret#30]
https://github.com/petzval/btferret/blob/52168f49cc993397f2942991c805861ba58ed0a8/btlib.h#L104C39-L104C39

Failing to compile in aarh64-linux-gnu. Function declaration doesn't match implementation. It compiles when changing declaration to:
int le_server(int(*callback)(int clientnode, int operation, int cticn),int timerds);

**Comment by petzval** [comment]
Thanks for finding that. Looks like that compiler is super-fussy.

**Comment by fabianmejia** [comment]
No worries. 
Your library it's pure gold!

    On Tuesday, November 21, 2023 at 06:16:51 AM EST, petzval ***@***.***> wrote:  
 
 


Thanks for finding that. Looks like that compiler is super-fussy.
