### ISSUE TITLE
Bonding inside docker

### ISSUE THREAD

**Issue by anujdeshpande** [petzval/btferret#44]
Hi

I am trying to see if bonding and pairing is possible when my btferret is running inside a docker container on the Pi. What I was looking for in the code or docs was a way to configure where the bonding information is stored so that I can store it in the docker volumes that is persistent.

Is this something handled by the underlying bluetooth library and not btferret? Because I couldn't find the code for that in the python files.

**Comment by petzval** [comment]
Pairing info is stored in the file /etc/btferret.dat. It is specified in the rwlinkey() function at line 9196 in btlib.c.
