### ISSUE TITLE
How to change the connection priority in btferret LE client ?

### ISSUE THREAD

**Issue by gregoiregentil** [petzval/btferret#51]
On Android, it's possible to change the BLE connection priority:

requestConnectionPriority (int connectionPriority)

https://developer.android.com/reference/android/bluetooth/BluetoothGatt#requestConnectionPriority(int)

Is this possible to do the same in btferret when connecting as a BLE client? Especially, I want to use CONNECTION_PRIORITY_HIGH.

**Comment by petzval** [comment]
Android's connection priority refers to the interval setting which is how often the Bluetooth adapter sends packets. See the functions set_le_interval, set_le_interval_update and set_le_interval_server.

**Comment by gregoiregentil** [comment]
Thank you.
